# Generated by Django 2.1.5 on 2019-02-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_auto_20190218_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
