# Generated by Django 2.1.5 on 2019-02-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_ranking_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='thumb',
        ),
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
