# Generated by Django 2.1.5 on 2019-02-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_auto_20190219_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='form',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranking',
            name='game8',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranking',
            name='last',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranking',
            name='match8',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranking',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='ranking',
            name='player',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranking',
            name='results',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
