# Generated by Django 2.1.5 on 2019-02-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_auto_20190223_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='event',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ranking',
            name='status',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
