# Generated by Django 2.1.5 on 2019-03-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='points',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teams',
            name='MD1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='MD2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='MS1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='MS2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='WD1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='WD2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='WS1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='WS2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='XD1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teams',
            name='XD2',
            field=models.CharField(max_length=50),
        ),
    ]
